import React, { useState, useMemo } from 'react';
import { Card, CardTitle } from '../ui/Card';
import { DataTable } from '../ui/DataTable';
import { reportsData, generatedFileLogsData, systemConfigData, transactionAnalyticsData } from '../../data/dummyData';
import type { ReportSummary, TransactionDetail, GeneratedFileLog } from '../../types';

export const ReportsAndGeneration: React.FC = () => {
    const [activeTab, setActiveTab] = useState<'analytics' | 'generation' | 'custom'>('analytics');
    const [isGenerationWizardOpen, setGenerationWizardOpen] = useState(false);
    const [generationType, setGenerationType] = useState<'TTUM' | 'NPCI Update' | null>(null);
    const [generatedFiles, setGeneratedFiles] = useState<GeneratedFileLog[]>(generatedFileLogsData);

    const handleGenerateFile = (channel: string, date: string) => {
        if (!generationType) return;
        const newFile: GeneratedFileLog = { id: `${Date.now()}`, file_name: `${generationType === 'TTUM' ? 'TTUM' : 'NPCI_UPDATE'}_${channel}_${date.replace(/-/g, '')}.csv`, file_type: generationType, channel, generated_by: 'anjali.mehta', generated_at: new Date().toISOString(), status: 'Generated' };
        setGeneratedFiles(prev => [newFile, ...prev]);
        setGenerationWizardOpen(false);
    };
    
    const reportColumns = [
        { header: 'Channel', accessor: 'channel' as keyof ReportSummary },
        { header: 'Report Type', accessor: 'report_type' as keyof ReportSummary },
        { header: 'Pending Transactions', accessor: 'pending_transactions' as keyof ReportSummary, render: (item: ReportSummary) => <span className={item.pending_transactions > 0 ? 'text-yellow-500' : ''}>{item.pending_transactions.toLocaleString()}</span> },
        { header: 'Pending Value (₹ Bn)', accessor: 'pending_value_bn' as keyof ReportSummary, render: (item: ReportSummary) => <span className={item.pending_value_bn > 0 ? 'text-yellow-500' : ''}>{item.pending_value_bn.toLocaleString()}</span> },
        { header: 'Report Date', accessor: 'report_date' as keyof ReportSummary },
    ];
    
    const generatedFileColumns = [
        { header: 'File Name', accessor: 'file_name' as keyof GeneratedFileLog },
        { header: 'File Type', accessor: 'file_type' as keyof GeneratedFileLog },
        { header: 'Channel', accessor: 'channel' as keyof GeneratedFileLog },
        { header: 'Generated By', accessor: 'generated_by' as keyof GeneratedFileLog },
        { header: 'Generated At', accessor: 'generated_at' as keyof GeneratedFileLog, render: (item: GeneratedFileLog) => new Date(item.generated_at).toLocaleString() },
        { header: 'Status', accessor: 'status' as keyof GeneratedFileLog },
    ];

    const ExportButtons: React.FC<{ onSchedule?: () => void }> = ({ onSchedule }) => (
         <div className="flex items-center space-x-2 mb-4">
            <button className="px-3 py-1 text-sm border rounded-md">Export as PDF</button>
            <button className="px-3 py-1 text-sm border rounded-md">Export as XLSX</button>
            {onSchedule && <button onClick={onSchedule} className="px-3 py-1 text-sm border rounded-md bg-primary-600 text-white">Schedule</button>}
         </div>
    );

    return (
        <div className="space-y-6">
            <Card>
                <div className="border-b border-gray-200 dark:border-gray-700">
                    <nav className="-mb-px flex space-x-8" aria-label="Tabs">
                        <button onClick={() => setActiveTab('analytics')} className={`whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm ${activeTab === 'analytics' ? 'border-primary-500 text-primary-600' : 'border-transparent text-gray-500 hover:border-gray-300'}`}>Analytics Reports</button>
                        <button onClick={() => setActiveTab('generation')} className={`whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm ${activeTab === 'generation' ? 'border-primary-500 text-primary-600' : 'border-transparent text-gray-500 hover:border-gray-300'}`}>File Generation</button>
                         <button onClick={() => setActiveTab('custom')} className={`whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm ${activeTab === 'custom' ? 'border-primary-500 text-primary-600' : 'border-transparent text-gray-500 hover:border-gray-300'}`}>Custom Reports</button>
                    </nav>
                </div>
                <div className="pt-6">
                    {activeTab === 'analytics' && (
                        <div>
                            <div className="flex justify-between items-center"><CardTitle>Settlement & Exception Reports</CardTitle><ExportButtons /></div>
                            <DataTable columns={reportColumns} data={reportsData} />
                        </div>
                    )}
                    {activeTab === 'generation' && (
                        <div>
                            <CardTitle>Generate Files for External Systems</CardTitle>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                                <div className="p-6 bg-gray-50 dark:bg-gray-800/50 rounded-lg text-center"><h4 className="font-semibold text-lg">TTUM for CBS Posting</h4><p className="text-sm my-2">Generate TTUM files for unmatched transactions.</p><button onClick={() => { setGenerationType('TTUM'); setGenerationWizardOpen(true); }} className="mt-2 px-4 py-2 text-sm rounded-md text-white bg-primary-600">Generate TTUM</button></div>
                                <div className="p-6 bg-gray-50 dark:bg-gray-800/50 rounded-lg text-center"><h4 className="font-semibold text-lg">NPCI Update File</h4><p className="text-sm my-2">Prepare update files for unreconciled transactions.</p><button onClick={() => { setGenerationType('NPCI Update'); setGenerationWizardOpen(true); }} className="mt-2 px-4 py-2 text-sm rounded-md text-white bg-primary-600">Generate NPCI File</button></div>
                            </div>
                            <div className="flex justify-between items-center"><CardTitle>Generation Logs</CardTitle><ExportButtons /></div>
                            <DataTable columns={generatedFileColumns} data={generatedFiles} />
                        </div>
                    )}
                    {activeTab === 'custom' && (
                        <div>
                            <CardTitle>Custom Report Builder</CardTitle>
                            <div className="p-4 bg-gray-50 dark:bg-gray-800/50 rounded-lg border space-y-4">
                               <div className="grid grid-cols-2 gap-4">
                                    <div><label className="text-sm font-medium">Dimensions</label><select multiple className="w-full h-24 mt-1 border-gray-300 rounded-md"><option>Channel</option><option>Status</option></select></div>
                                    <div><label className="text-sm font-medium">Metrics</label><select multiple className="w-full h-24 mt-1 border-gray-300 rounded-md"><option>Total Volume</option><option>Total Value</option></select></div>
                               </div>
                               <button className="px-4 py-2 text-sm rounded-md text-white bg-primary-600">Generate Report</button>
                            </div>
                            <div className="mt-6">
                                <div className="flex justify-between items-center"><h4 className="font-semibold">Custom Report: Volume by Channel</h4><ExportButtons onSchedule={() => alert('Scheduling UI would open here.')} /></div>
                                <DataTable columns={[{header: 'Channel', accessor: 'channel'}, {header: 'Volume (Mn)', accessor: 'volume_mn'}]} data={transactionAnalyticsData} />
                            </div>
                        </div>
                    )}
                </div>
            </Card>
            {isGenerationWizardOpen && generationType && <GenerationWizard type={generationType} onClose={() => setGenerationWizardOpen(false)} onGenerate={handleGenerateFile} />}
        </div>
    );
};

const GenerationWizard: React.FC<{ type: 'TTUM' | 'NPCI Update', onClose: () => void, onGenerate: (channel: string, date: string) => void }> = ({ type, onClose, onGenerate }) => {
    const [channel, setChannel] = useState(systemConfigData.supported_channels[0]);
    const [date, setDate] = useState(new Date().toISOString().split('T')[0]);

    const handleSubmit = () => onGenerate(channel, date);

    return (
        <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex items-center justify-center p-4">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-lg">
                <header className="p-4 border-b"><h2 className="text-xl font-semibold">Generate {type} File</h2></header>
                <main className="p-6 space-y-4">
                    <div><label>Channel</label><select value={channel} onChange={e => setChannel(e.target.value)} className="mt-1 block w-full border-gray-300 rounded-md">{systemConfigData.supported_channels.map(c => <option key={c} value={c}>{c}</option>)}</select></div>
                    <div><label>Date Range</label><input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-1 block w-full border-gray-300 rounded-md" /></div>
                </main>
                <footer className="flex justify-end p-4 bg-gray-50 dark:bg-gray-800/50 border-t space-x-3">
                    <button onClick={onClose} className="px-4 py-2 border rounded-md">Cancel</button>
                    <button onClick={handleSubmit} className="px-4 py-2 rounded-md text-white bg-primary-600">Generate File</button>
                </footer>
            </div>
        </div>
    )
}